apiVersion: v1
kind: PersistentVolume
metadata:
  name: eight-sqlite-pv
  namespace: eight-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/eight-sqlite"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eight-sqlite-pvc
  namespace: eight-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual