apiVersion: v1
kind: Service
metadata:
  name: eight-service
  namespace: eight-app
spec:
  selector:
    app: eight
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer